#README rust-app

* What is this?

This is a minimal rust application that invokes a native java library (=java-lib= project).

The Rust bindings for the Java library are generated by the =build.rs= file.
- All the =println= statements in that file are important, they are used for compilation instructions...
- All the references to =helloapi= follow naming conventions of the Java native library artifacts.

* How to build?

You'll need a C compiler (i.e. gcc). It is assumed that you've got the [[https://llvm.org/][LLVM]] toolchain installed, as well as the [[https://doc.rust-lang.org/cargo/][cargo]] build tool. At the root of this project, run the command below.

#+begin_src sh
cargo build
#+end_src

* How to run?

** Run instructions

Once the Rust project is built in the previous step, run the command below.

#+begin_src sh
LD_LIBRARY_PATH=../java-lib/build/native/nativeBuild ./target/debug/rust-app
#+end_src

 If you have moved the 'relative location' of the =java-lib= project elsewhere on your machine, you need to set an environment variable called =LIBHELLOAPI_PATH= and point it to the location of the native java library and header files.

** Sample execution output

#+begin_src text
  $ LD_LIBRARY_PATH=../java-lib/build/native/nativeBuild ./target/debug/rust-app
  Hello World
  $
#+end_src
   
